-- Goals — PostgreSQL schema.
--
-- Applied idempotently on every startup (see database.py:init_schema).
-- Ordering matters: types, then tables, then indexes.

-- ── ENUMS ────────────────────────────────────────────────────────────────────
DO $$ BEGIN
    CREATE TYPE goal_type AS ENUM ('daily', 'weekly_x');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE first_day AS ENUM ('sunday', 'monday');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ── GOALS ────────────────────────────────────────────────────────────────────
-- `version` backs the optimistic-concurrency check in PUT /api/goals/{id}.
-- The CHECK constraints encode the same rules as models.py so the DB stays
-- correct even if a write path ever bypasses Pydantic.
CREATE TABLE IF NOT EXISTS goals (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT      NOT NULL,
    type          goal_type NOT NULL,
    is_negative   BOOLEAN   NOT NULL DEFAULT FALSE,
    times_per_week SMALLINT,
    times_per_day  SMALLINT,
    reward_rules  JSONB     NOT NULL DEFAULT '[]'::jsonb,
    "order"       INTEGER   NOT NULL DEFAULT 0,
    version       INTEGER   NOT NULL DEFAULT 1,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT goals_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT goals_reward_rules_is_array CHECK (jsonb_typeof(reward_rules) = 'array'),
    -- weekly_x goals carry times_per_week (1-7) and no times_per_day;
    -- daily goals carry times_per_day (>=1) and no times_per_week.
    --
    -- Wrapped in COALESCE(..., FALSE) deliberately: a CHECK passes when it
    -- evaluates to NULL, and with BOTH cadence columns NULL every comparison
    -- is NULL, so the bare expression would accept the exact invalid row this
    -- constraint exists to reject.
    CONSTRAINT goals_shape CHECK (COALESCE(
        (type = 'weekly_x'
            AND times_per_week BETWEEN 1 AND 7
            AND times_per_day IS NULL)
        OR
        (type = 'daily'
            AND times_per_day >= 1
            AND times_per_week IS NULL),
        FALSE
    ))
);

-- Rebuild goals_shape on databases created before the COALESCE fix above.
-- The original form evaluated to NULL (and so passed) when both cadence
-- columns were NULL. Drop-and-recreate rather than edit in place, since
-- CREATE TABLE IF NOT EXISTS won't touch an existing constraint.
ALTER TABLE goals DROP CONSTRAINT IF EXISTS goals_shape;
ALTER TABLE goals ADD CONSTRAINT goals_shape CHECK (COALESCE(
    (type = 'weekly_x' AND times_per_week BETWEEN 1 AND 7 AND times_per_day IS NULL)
    OR
    (type = 'daily' AND times_per_day >= 1 AND times_per_week IS NULL),
    FALSE
));

-- Case-insensitive unique name. Replaces the Mongo collation index plus the
-- application-level find_one duplicate check, which raced under concurrency.
CREATE UNIQUE INDEX IF NOT EXISTS goals_name_lower_key
    ON goals (lower(btrim(name)));

CREATE INDEX IF NOT EXISTS goals_order_idx ON goals ("order");


-- ── GOAL_WEEKS ───────────────────────────────────────────────────────────────
-- Per-week enrollment. `snapshot` is a deliberate denormalization: it freezes
-- the goal's config as it was during that week so historical weeks keep
-- rendering correctly after the live goal is edited or deleted. It is JSONB
-- (not columns) precisely because it must NOT track the live schema.
--
-- NOTE: no FK to goals. Deleting a goal keeps past weeks intact (the delete
-- endpoint only clears the current week), and the snapshot is what those weeks
-- render from. A FK with CASCADE would destroy that history.
CREATE TABLE IF NOT EXISTS goal_weeks (
    goal_id    BIGINT NOT NULL,
    week_start DATE   NOT NULL,
    enabled    BOOLEAN NOT NULL DEFAULT TRUE,
    snapshot   JSONB   NOT NULL DEFAULT '{}'::jsonb,

    PRIMARY KEY (goal_id, week_start)
);

CREATE INDEX IF NOT EXISTS goal_weeks_week_enabled_idx
    ON goal_weeks (week_start, enabled);


-- ── LOGS ─────────────────────────────────────────────────────────────────────
-- One row per (goal, day). `slots` is a boolean array rather than a child
-- table: slots are always read and written as a whole array, are bounded by
-- times_per_day, and have no identity of their own.
--
-- Also no FK to goals, for the same history-preservation reason as goal_weeks:
-- deleting a goal clears only the current week's logs; past logs survive.
CREATE TABLE IF NOT EXISTS logs (
    goal_id BIGINT  NOT NULL,
    date    DATE    NOT NULL,
    slots   BOOLEAN[] NOT NULL,

    PRIMARY KEY (goal_id, date),
    CONSTRAINT logs_slots_not_empty CHECK (cardinality(slots) >= 1),
    -- BOOLEAN[] NOT NULL only forbids a NULL *array*; {true,NULL} and {NULL}
    -- would still pass. A NULL element breaks LogOut.slots (List[bool]) on
    -- every later read of that week, so reject it at the source.
    CONSTRAINT logs_slots_no_nulls CHECK (array_position(slots, NULL) IS NULL)
);

CREATE INDEX IF NOT EXISTS logs_date_idx ON logs (date);

-- Add the no-NULLs guard to databases created before it existed.
ALTER TABLE logs DROP CONSTRAINT IF EXISTS logs_slots_no_nulls;
ALTER TABLE logs ADD CONSTRAINT logs_slots_no_nulls
    CHECK (array_position(slots, NULL) IS NULL);


-- ── SETTINGS ─────────────────────────────────────────────────────────────────
-- Single-row table. The `id` CHECK enforces that: only one row can ever exist,
-- replacing Mongo's {"_id": "global"} convention.
CREATE TABLE IF NOT EXISTS settings (
    id                BOOLEAN PRIMARY KEY DEFAULT TRUE,
    timezone          TEXT      NOT NULL,
    first_day_of_week first_day NOT NULL,
    currency          TEXT      NOT NULL,
    start_date        DATE,

    CONSTRAINT settings_singleton CHECK (id)
);


-- ── DEVICES ──────────────────────────────────────────────────────────────────
-- FCM push tokens. Mongo had a TTL index auto-expiring rows 60 days after
-- last_seen_at; Postgres has no TTL, so day_watcher prunes stale rows once a
-- day (see prune_stale_devices).
CREATE TABLE IF NOT EXISTS devices (
    token             TEXT PRIMARY KEY,
    app_session_id    TEXT,
    widget_session_id TEXT,
    platform          TEXT NOT NULL DEFAULT 'android',
    last_seen_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS devices_last_seen_idx ON devices (last_seen_at);


-- ── GLOBAL SEQUENCE ──────────────────────────────────────────────────────────
-- Monotonic counter for client sync. Mongo used an atomic CAS on a singleton
-- doc; here the CAS lives in a small table so we can compare-and-set against
-- the client's X-Sequence value. A native SEQUENCE can't do that (no way to
-- conditionally bump), so a single-row table with UPDATE ... WHERE seq = $1 is
-- the correct primitive.
CREATE TABLE IF NOT EXISTS sequence (
    id  BOOLEAN PRIMARY KEY DEFAULT TRUE,
    seq BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT sequence_singleton CHECK (id)
);

INSERT INTO sequence (id, seq) VALUES (TRUE, 0) ON CONFLICT (id) DO NOTHING;
